### ISSUE TITLE
Verify kevinkotowski

### ISSUE THREAD

**Issue by schnittstabil** [schnittstabil/the-app-is-broken#1]
Verify the github user @kevinkotowski is really the author of [The App is Broken](https://8thlight.com/blog/kevin-kotowski/2017/01/16/broken-software.html).

**Comment by kevinkotowski** [comment]
Hi there, I am the author. I hope you liked it. It looks like you are suggesting a smart integration for Github issues and PRs with what you posted here.

**Comment by schnittstabil** [comment]
@kevinkotowski Many thanks, I wasn't 100% sure.

Yes, Github provides support for that, e.g. if you click on _New issue_, then the `.github/issue_template.md` will be used. It's more an educational/showcase project, about how OSS projects can improve issue reporting, based on a well-conceived template.

Thanks for your blog entry and the template, I hope you don't mind that I've copied your template one-to-one.

**Comment by kevinkotowski** [comment]
I don't mind at all. The more people that focus on a simple approach, the happier they will be. Feel free to reference my blog post to others that are struggling!
